/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 */
export type AccountDataSchema = [
  {
    bankNumber: 12;
    extendedBankNumber: 912;
    branchNumber: number;
    accountNumber: number;
    partyPreferredIndication: 0;
    partyAccountInvolvementCode: 1 | 201;
    accountDealDate: 0;
    accountUpdateDate: number | 0;
    metegDoarNet: 0 | 1;
    kodHarshaatPeilut: 1 | 3;
    accountClosingReasonCode: 0 | 1;
    /**
     * Branch number with account number and two spaces in between
     */
    productLabel: string;
    accountAgreementOpeningDate: 0;
    serviceAuthorizationDesc: "לא חתום" | "פעולות ומידע";
    branchTypeCode: 0 | 2;
    mymailEntitlementSwitch: 0 | 1;
  },
  ...{
    bankNumber: 12;
    extendedBankNumber: 912;
    branchNumber: number;
    accountNumber: number;
    partyPreferredIndication: 0;
    partyAccountInvolvementCode: 1 | 201;
    accountDealDate: 0;
    accountUpdateDate: number | 0;
    metegDoarNet: 0 | 1;
    kodHarshaatPeilut: 1 | 3;
    accountClosingReasonCode: 0 | 1;
    /**
     * Branch number with account number and two spaces in between
     */
    productLabel: string;
    accountAgreementOpeningDate: 0;
    serviceAuthorizationDesc: "לא חתום" | "פעולות ומידע";
    branchTypeCode: 0 | 2;
    mymailEntitlementSwitch: 0 | 1;
  }[]
];
