/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ForeignTransactionsBusinessSchema {
  balancesAndLimitsDataList: {
    accountNumber: number;
    bankNumber: 12 | 0;
    branchNumber: number;
    creditLimits: string[];
    currencyCode: number;
    currencyLongDescription: string;
    currencyShortedDescription: string;
    currencySwiftCode: string;
    currencySwiftDescription: string;
    currentAccountLimitsAmount: 0;
    currentBalance: 0;
    currentBalanceExchangeRateWayDescription: null;
    currentBalanceExchangeRateWayCode: 0;
    detailedAccountTypeCode: 142;
    detailedAccountTypeShortedDescription: string;
    formattedLastEventDate: null;
    formattedRetrievalMaxDate: string | null;
    formattedRetrievalMinDate: string | null;
    lastBalance: 0;
    lastBalanceExchangeRateWayCode: 0;
    lastEventDate: 0;
    messages:
      | {
          messageDescription: string;
          messageCode: 3;
        }[]
      | null;
    numItemsPerPage: number;
    outputArrayRecordSum3: 0;
    outputArrayRecordSum4: 0;
    pendingBalance: 0;
    rateExerciseDescription: null;
    rateRealizationCode: 0;
    retrievalMaxDate: number;
    retrievalMinDate: number;
    /**
     * @minItems 0
     * @maxItems 0
     */
    revaluatedCurrentBalance: [];
    transactionResultCode: number;
    transactions: {
      accountName: string | null;
      activityDescription: string;
      activityTypeCode: number;
      comments: null;
      commentExistenceSwitch: 0;
      contraAccountFieldNameLable: string | null;
      contraAccountNumber: number;
      contraBankNumber: number;
      contraBranchNumber: number;
      contraCurrencyCode: 0 | 1 | 19 | 27 | 78 | 100;
      currencyLongDescription: string;
      currencyRate: number;
      currencySwiftCode: string;
      currentBalance: number;
      dataGroupCode: 0;
      displayCreditAccountDetails?: 0 | 1;
      eventActivityTypeCode: number;
      eventAmount: number;
      eventDetails: string | null;
      eventNumber: number;
      executingDate: number;
      expendedExecutingDate: string;
      formattedExecutingDate: string;
      formattedValueDate: string;
      metadata?: {
        attributes: {
          contraAccountFieldNameLable?: {
            disabled?: "true";
            hidden?: "true";
          };
          contraAccountNumber?: {
            disabled?: "true";
            hidden?: "true";
          };
          contraBankNumber?: {
            disabled?: "true";
            hidden?: "true";
            [k: string]: unknown;
          };
          contraBranchNumber?: {
            disabled?: "true";
            hidden?: "true";
            [k: string]: unknown;
          };
          contraCurrencyCode?: {
            disabled?: "true";
            hidden?: "true";
            [k: string]: unknown;
          };
          currencyRate?: {
            disabled?: "true";
            hidden?: "true";
            [k: string]: unknown;
          };
          dataGroupCode?: {
            disabled?: "true";
            hidden?: "true";
            [k: string]: unknown;
          };
          originalEventKey?: {
            disabled?: "true";
            hidden?: "true";
            [k: string]: unknown;
          };
          rateFixingCode?: {
            disabled?: "true";
            hidden?: "true";
            [k: string]: unknown;
          };
        };
        links: {};
      };
      originalEventKey: 0;
      originalSystemId: number;
      rateFixingCode: number;
      rateFixingDescription: string;
      rateFixingShortDescription: string;
      recordSerialNumber: number;
      referenceCatenatedNumber: number;
      referenceNumber: number;
      transactionType: string;
      urlAddress: string | null;
      validityDate: number;
      valueDate: number;
    }[];
    withdrawalBalance: 0;
  }[];
  balancesAndTransactionsCurrencyCombo: {
    currencyCode: null;
  };
  currancyBalanceData: null;
  currencyCode: null;
  detailedAccountTypeCode: null;
  displayedRevaluationCurrencyCode: 0;
  foreignCurrencyBalancesData: null;
  formattedValidityDate: null;
  messages: null;
  metadata?: {
    links: {};
    messages: {
      messageCode: 11040 | 330 | 11039 | 11038;
      messageDescription: string;
      severity: "I";
    }[];
  };
  outputArrayRecordSum2: 0;
  pdfUrl: null;
  rateFixingDescription: null;
  validityDate: 0;
}
