/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Deposits = {
  data: {
    metadata: {
      attributes: {
        actualCurrencyRate: {
          hidden: string;
          [k: string]: unknown;
        };
        lastIndexRate: {
          hidden: string;
          [k: string]: unknown;
        };
        basicIndexValue: {
          hidden: string;
          [k: string]: unknown;
        };
        basicCurrencyRate: {
          hidden: string;
          [k: string]: unknown;
        };
        standingOrderAmount: {
          hidden: string;
          [k: string]: unknown;
        };
        linkagePercent: {
          hidden: string;
          [k: string]: unknown;
        };
        ratePercentFactor: {
          hidden: string;
          [k: string]: unknown;
        };
        fixedInterestRate: {
          hidden: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      links: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    shortProductName: "פריים";
    principalAmount: number;
    revaluedTotalAmount: number;
    endExitDate: number;
    paymentDate: number;
    statedAnnualInterestRate: number;
    hebrewPurposeDescription: "לא רלוונטי";
    objectiveAmount: number;
    objectiveDate: number;
    agreementOpeningDate: number;
    eventWithdrawalAmount: number;
    startExitDate: number;
    periodUntilNextEvent: number;
    renewalDescription: "פיקדון מתחדש" | 'יפרע לעו"ש';
    requestedRenewalNumber: number;
    interestBaseDescription: "פריים";
    interestTypeDescription: "משתנה";
    spreadPercent: number;
    variableInterestDescription: string;
    adjustedInterest: number;
    interestCalculatingMethodDescription: "קו ישר";
    interestCreditingMethodDescription: "לקרן הפיקדון";
    interestPaymentDescription: "תחנה";
    nominalInterest: number;
    depositSerialId: number;
    linkageBaseDescription: null;
    renewalCounter: number;
    productFreeText: string;
    partyTextId: number;
    actualIndexRate: number;
    interestTypeCode: number;
    productNumber: number;
    productPurposeCode: number;
    detailedAccountTypeCode: number;
    formattedEndExitDate: string;
    formattedPaymentDate: string;
    formattedObjectiveDate: null;
    formattedAgreementOpeningDate: string;
    formattedStartExitDate: string;
    lienDescription: "משועבד" | "מבטיח אשראי";
    withdrawalEnablingIndication: number;
    renewalEnablingIndication: number;
    standingOrderEnablingIndication: number;
    additionEnablingIndication: number;
    timeUnitDescription: "ימים";
    formattedRevaluedTotalAmount: null;
    warningExistanceIndication: number;
    renewalDateExplanation: "תחנה קרובה" | 'ייפרע לעו"ש בתאריך';
    expectedRepaymentSwitch: 0 | 1;
  }[];
  source: "israeliCurrencyDeposit";
  validityDate: number;
  validityTime: number;
  israeliCurrencyDepositPrincipalBalanceAmount: number;
  depositsRevaluedAmount: number;
  formattedValidityTime: string;
  formattedDate: string;
  amount: number;
  revaluatedAmount: number;
  messages: {
    messageCode: 803 | 804 | 805 | 821 | 822 | 823 | 824 | 825 | 826;
    messageDescription:
      | "בכל מקרה לא תפחת הריבית על הפיקדון משיעור 0% בשנה."
      | 'הוראת משיכה/אי חידוש לפיקדון צמוד מט"ח יש לתת שני ימי עסקים לפחות לפני תאריך התחנה/החידוש.'
      | "שערוך הפיקדונות המובנים מחושב בשיטה דומה, אך לא זהה, לתנאי ההתקשרות ואין בנתונים כדי לחייב את הבנק או לשמש אסמכתא לפדיון או משיכה."
      | "פעולה המבוצעת בפיקדונות בשקלים עד השעה 18:30 (בימי ו' וערבי חג עד 14:00) ביום שהינו יום עסקים, נקלטת מיד עם אישורה ומשתקפת מיידית במסך פירוט פיקדונות."
      | "לאחר קליטת הפעולה לא ניתן יהיה לבטלה."
      | "הוראה הניתנת לאחר השעה 18:30 ( בימי ו' וערבי חג - לאחר השעה 14:00 ) תשתקף בחשבונך החל מהשעה 02:00 ועד למועד זה ניתן יהיה לבטלה."
      | "הוראה הניתנת ביום שאינו יום עסקים, תבוצע ביום העסקים הבא ותשתקף בחשבונך החל מהשעה 02:00 של אותו יום ועד למועד זה ניתן יהיה לבטלה."
      | "הוראה לביצוע עתידי ניתנת לביטול עד לשעה 02:00 של יום ערך הביצוע."
      | 'במסך "סטטוס הוראות בפיקדונות" ניתן לצפות בסטטוס הפעולה. אם סטטוס הפעולה הינו "ממתין לביצוע" - ניתן לבטלה.';
    messageTypeCode: "I";
  }[];
}[];

export interface HapoalimDepositsSchema {
  metadata: {
    messages:
      | []
      | [
          {
            messageDescription: string;
            messageCode: number;
            severity: string;
            [k: string]: unknown;
          },
          ...unknown[]
        ];
    links: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  list: Deposits;
  depositsWrapperData: Deposits;
}
