/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ILSCheckingTransactionsDataSchema {
  comments: string[];
  message: string[];
  metadata?: {
    links: {};
    messages: {
      messageCode: 11040 | 1260003;
      messageDescription: string;
      messagePurposeCategoryCode: "1";
      severity: "I";
    }[];
  };
  numItemsPerPage: number;
  pdfUrl: string;
  retrievalTransactionData: {
    accountNumber: number;
    balanceAmountDisplayIndication: "Y";
    bankNumber: 12;
    branchNumber: number;
    eventCounter: number;
    formattedRetrievalEndDate: string;
    formattedRetrievalMaxDate: string;
    formattedRetrievalMinDate: string;
    formattedRetrievalStartDate: string;
    joinPfm: false | true;
    retrievalEndDate: number;
    retrievalMaxDate: number;
    retrievalMinDate: number;
    retrievalStartDate: number;
  };
  transactions: {
    activityDescription: string;
    activityDescriptionIncludeValueDate: string | null;
    activityTypeCode: number;
    beneficiaryDetailsData: {
      messageDetail?: string | null;
      messageHeadline?: string | null;
      partyHeadline?: string | null;
      partyName?: string | null;
      recordNumber?: number;
      tableNumber?: number;
      beneficiaryDetails?: string | null;
    } | null;
    comment: string | null;
    commentExistenceSwitch: 0;
    contraAccountNumber: number;
    contraAccountTypeCode: number;
    contraBankNumber: number;
    contraBranchNumber: number;
    currentBalance: number;
    dataGroupCode: number;
    details: string | null;
    differentDateIndication: string;
    englishActionDesc: string | null;
    /**
     * Income (1) or expense (2)
     */
    eventActivityTypeCode: 1 | 2;
    eventAmount: number;
    eventDate: number;
    eventId: 0 | 184 | 8552511030540 | 8552553828500;
    executingBranchNumber: number;
    expandedEventDate: string;
    fieldDescDisplaySwitch: 0 | 1;
    formattedEventDate: string;
    formattedOriginalEventCreateDate: null;
    formattedValueDate: string;
    internalLinkCode: number;
    marketingOfferContext: 0;
    offerActivityContext: string | null;
    originalEventCreateDate: number;
    pfmDetails: string | null;
    recordNumber: number;
    referenceCatenatedNumber: number;
    referenceNumber: number;
    rejectedDataEventPertainingIndication: string;
    serialNumber: number;
    tableNumber: number;
    textCode: number;
    /**
     * Fixed (REGULAR) or still in process/temporary (TODAY)
     */
    transactionType: "REGULAR" | "TODAY";
    valueDate: number;
    displayCreditAccountDetails?: 0 | 1;
    displayRTGSIncomingTrsDetails: 0 | 1;
  }[];
}
