/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IsracardDashboardMonth {
  Header: {
    Status: string;
    Message: string;
  };
  DashboardMonthBean: {
    totalDebitShekel: string;
    totalDebitDollar: string;
    totalDebitEuro: string;
    cardType: string;
    statementDate: {
      billingDateCode: string;
      billingDate: string;
      totalShekel: string;
      totalDollar: string;
      totalEuro: string;
      cardType: string;
      billingDateMore: string;
      statementDateCard: null;
    }[];
    cardsCharges: {
      period: string;
      billingDate: string;
      workingDate: string;
      cardNumber: string;
      cardIndex: string;
      moreNumberDays: string;
      cardType: string;
      billingDateMore: string;
      billingSumSekel: string;
      billingSumDollar: string;
      billingSumEuro: string;
      cardStatus: string;
      idType: string;
    }[];
    extraCards: string;
    returnCode: string;
    message: string;
    returnMessage: string;
    displayProperties: string;
    tablePageNum: string;
    isError: string;
    isCaptcha: string;
    isButton: string;
    clientIpAddress?: string;
  };
}
