/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^card[0-9]$".
 */
export type Card = {
  clientIpAddress?: null;
  currentId: "0" | "1" | "2" | "3" | "4" | null;
  displayProperties: null;
  holderId: string;
  holderName: null;
  isButton: "false";
  isCaptcha: "false";
  isError: "false";
  message: null;
  returnCode: null;
  returnMessage: null;
  siteName: null;
  stage: null;
  tablePageNum: "0";
  totalDollar: "0" | null;
  totalEuro: "0" | null;
  totalNis: string | null;
  bcKey?: null;
}[];

export interface IsracardCardsTransactionsList {
  Header: {
    ErrorPage?: string;
    Status: "1" | "-2";
    Message: null;
  };
  CardsTransactionsListBean: {
    card0: Card;
    card6Digits: string;
    cardIdx: "0,1,2,3,4" | "0,1,2,3" | "0,1,2" | "0,1" | "0";
    cardNumberList: string[];
    cardNumberTail: string;
    clientIpAddress?: string;
    currentDate: string;
    dateList: string[];
    displayProperties: string;
    endDate: null;
    Index0: Index;
    isButton: "false";
    isCaptcha: "false";
    isCashBack: "false";
    isError: "false";
    isShowDealsInboundForCharge: "yes" | "NO";
    isShowDealsInboundForInfo: "NO";
    isThereData: "1" | null;
    isTooManyRecords: null;
    message: null;
    moed: string;
    month: "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12";
    payDay: "10" | "02" | "15" | null;
    paymentPercent: null;
    paymentSum: "000" | "280";
    returnCode: null;
    returnMessage: null;
    selectedCardIndex: "0" | "1" | "2" | "3" | "4";
    selectedCardInfo: string;
    selectedDateIndex: "23" | "24";
    siteName: null;
    specificDate: null;
    stage: null;
    startDate: null;
    tablePageNum: "0";
    totalChargeDollar: null;
    totalChargeEuro: null;
    totalChargeNis: string | null;
    totalDebit: null;
    userId: string;
    year:
      | "2010"
      | "2011"
      | "2012"
      | "2013"
      | "2014"
      | "2015"
      | "2016"
      | "2017"
      | "2018"
      | "2019"
      | "2020"
      | "2021"
      | "2022";
    bcKey?: null;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^Index[0-9]$".
 */
export interface Index {
  "@AllCards": "AllCards";
  CurrentCardTransactions: {
    "@cardTransactions": string;
    txnAbroad?:
      | {
          adendum: null;
          cardIndex: "0" | "1" | "2" | "3";
          city: string | null;
          clientIpAddress?: null;
          currencyId: ("NIS" | "USD" | "EUR") | null;
          currentPaymentCurrency:
            | "NIS"
            | "USD"
            | "LEU"
            | "SUR"
            | "EUR"
            | "DKK"
            | "TRY"
            | "GBP"
            | "CHF"
            | "HUF"
            | "AUD"
            | "INR"
            | "HKD"
            | "YUN"
            | "JPY"
            | "SGD"
            | "OMR"
            | "CZE"
            | "NOK"
            | null;
          dealsInbound: null;
          dealSum: null;
          dealSumOutbound: string | null;
          dealSumType: null;
          displayProperties: null;
          fullPaymentDate: string | null;
          fullPurchaseDate: null;
          fullPurchaseDateOutbound: string | null;
          fullSupplierNameHeb: null;
          fullSupplierNameOutbound: string;
          horaatKeva: null;
          isButton: "false";
          isCaptcha: "false";
          isError: "false";
          isHoraatKeva: "false";
          isShowDealsOutbound: "_" | null;
          isShowLinkForSupplierDetails: null;
          message: null;
          moreInfo: null;
          paymentDate: string | null;
          paymentSum: null;
          paymentSumOutbound: string;
          paymentSumSign: null;
          purchaseDate: null;
          purchaseDateOutbound: string | null;
          returnCode: null;
          returnMessage: null;
          siteName: null;
          solek: null;
          specificDate: null;
          stage: null;
          supplierId: null;
          supplierName: null;
          supplierNameOutbound: string;
          tablePageNum: "0";
          voucherNumber: string | null;
          voucherNumberRatz: null;
          voucherNumberRatzOutbound: string;
          bcKey?: null;
        }[]
      | null;
    txnInfo?: null;
    txnIsrael?:
      | {
          adendum: null;
          cardIndex: "0" | "1" | "2" | "3" | "4";
          city: null;
          clientIpAddress?: null;
          currencyId: 'ש"ח' | "דולר" | null;
          currentPaymentCurrency: null;
          dealsInbound: "yes" | "NO";
          dealSum: string | null;
          dealSumOutbound: null;
          dealSumType: "1" | "T" | "P" | null;
          displayProperties: null;
          fullPaymentDate: null;
          fullPurchaseDate: string | null;
          fullPurchaseDateOutbound: null;
          fullSupplierNameHeb: string | null;
          fullSupplierNameOutbound: null;
          horaatKeva: "K" | null;
          isButton: "false";
          isCaptcha: "false";
          isError: "false";
          isHoraatKeva: "false" | "true";
          isShowDealsOutbound: null;
          isShowLinkForSupplierDetails: "yes" | "NO";
          message: null;
          moreInfo: string | null;
          paymentDate: null;
          paymentSum: string | null;
          paymentSumOutbound: null;
          paymentSumSign: "-" | null;
          purchaseDate: string | null;
          purchaseDateOutbound: null;
          returnCode: null;
          returnMessage: null;
          siteName: null;
          solek: "I" | "L" | "V" | "_" | null;
          specificDate: null;
          stage: null;
          supplierId: (
            | {
                [k: string]: unknown;
              }
            | "0"
          ) &
            string;
          supplierName: string | null;
          supplierNameOutbound: null;
          tablePageNum: "0";
          voucherNumber: string | null;
          voucherNumberRatz: string;
          voucherNumberRatzOutbound: null;
          bcKey?: null;
        }[]
      | null;
  }[];
}
