sources:
  - name: Payper
    handler:
      jsonSchema:
        baseUrl: 'https://payper.co.il/app/api'
        operationHeaders:
          API_KEY: '{env.PAYPER_MESH_AUTH_TOKEN}'
          Content-Type: application/json
          Accept: application/json
        operations:
          - type: Query
            field: getExpenses
            path: /pull_expenses
            method: POST
            requestSchema: ./json-schemas/payperSchema.json#/definitions/getExpensesRequest
            responseSchema: ./json-schemas/payperSchema.json#/definitions/getExpensesResponse

          # getCustomerGeneralLedger
          # getListOfInventory
          # getQuantityForItem

    transforms:
      - resolversComposition:
          mode: bare
          compositions:
            - resolver: Query.getExpenses
              composer: src/resolvers/getExpensesResolver
serve:
  browser: false

sdk:
  generateOperations:
    selectionSetDepth: 2

require:
  - ts-node/register/transpile-only
