sources:
  - name: GreenInvoice
    handler:
      jsonSchema:
        baseUrl: 'https://api.greeninvoice.co.il/api/v1'
        operationHeaders:
          Authorization: Bearer {context.authToken}
          Content-Type: application/json
        operations:
          - type: Mutation
            field: addExpense
            path: /expenses
            method: POST
            requestSchema: ./json-schemas/greenInvoice.json#/definitions/addExpenseRequest
            responseSchema: ./json-schemas/greenInvoice.json#/definitions/addExpenseResponse

          - type: Query
            field: getExpense
            path: /expenses/{args.id}
            method: GET
            requestSchema: ./json-schemas/greenInvoice.json#/definitions/getExpenseRequest
            responseSchema: ./json-schemas/greenInvoice.json#/definitions/getExpenseResponse

          - type: Query
            field: updateExpense
            path: /expenses/{args.id}
            method: PUT
            requestSchema: ./json-schemas/greenInvoice.json#/definitions/updateExpenseRequest
            responseSchema: ./json-schemas/greenInvoice.json#/definitions/updateExpenseResponse

          - type: Query
            field: searchExpenses
            path: /expenses/search
            method: POST
            requestSchema: ./json-schemas/greenInvoice.json#/definitions/searchExpensesRequest
            responseSchema: ./json-schemas/greenInvoice.json#/definitions/searchExpensesResponse

          - type: Mutation
            field: addExpenseDraftByFile
            path: /expenses/file
            method: POST
            requestSchema: ./json-schemas/greenInvoice.json#/definitions/addExpenseDraftByFileRequest
            responseSchema: ./json-schemas/greenInvoice.json#/definitions/addExpenseDraftByFileResponse

          - type: Query
            field: searchExpenseDrafts
            path: /expenses/drafts/search
            method: POST
            requestSchema: ./json-schemas/greenInvoice.json#/definitions/searchExpenseDraftsRequest
            responseSchema: ./json-schemas/greenInvoice.json#/definitions/searchExpenseDraftsResponse

serve:
  browser: false

sdk:
  generateOperations:
    selectionSetDepth: 2

require:
  - ts-node/register/transpile-only
