sources:
  - name: GreenInvoice
    handler:
      jsonSchema:
        endpoint: 'https://api.greeninvoice.co.il/api/v1'
        operationHeaders:
          Authorization: Bearer {context.authToken}
          Content-Type: application/json
        operations:
          - type: Mutation
            field: addExpense
            path: /expenses
            method: POST
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseRequest
            responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseResponse

          - type: Query
            field: getExpense
            path: /expenses/{args.id}
            method: GET
            argTypeMap:
              id:
                type: string
                nullable: false
            responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/getExpenseResponse

          - type: Query
            field: updateExpense
            path: /expenses/{args.id}
            method: PUT
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/updateExpenseRequest
            responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/updateExpenseResponse

          - type: Query
            field: searchExpenses
            path: /expenses/search
            method: POST
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/searchExpensesRequest
            responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/searchExpensesResponse

          - type: Mutation
            field: addExpenseDraftByFile
            path: /expenses/file
            method: POST
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseDraftByFileRequest
            responseByStatusCode:
              201:
                responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseDraftByFileResponse
              400:
                responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/generalErrorResponse
              404:
                responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/generalErrorResponse

          - type: Query
            field: searchExpenseDrafts
            path: /expenses/drafts/search
            method: POST
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/searchExpenseDraftsRequest
            responseByStatusCode:
              201:
                responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/searchExpenseDraftsResponse
              404:
                responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/generalErrorResponse

serve:
  browser: false

sdk:
  generateOperations:
    selectionSetDepth: 2
